name: Release

on:
  release:
    types: [published]

defaults:
  run:
    shell: pwsh

jobs:
  deploy:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: Install docfx
      run: choco install docfx -y
    # - name: Set up QEMU
    #   uses: docker/setup-qemu-action@v1
    # - name: Set up Docker Buildx
    #   uses: docker/setup-buildx-action@v1
    # - name: Login to DockerHub
    #   uses: docker/login-action@v1
    #   with:
    #     username: ${{ secrets.DOCKERHUB_USERNAME }}
    #     password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and Deploy packages
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.NUGET_TOKEN }}
      run: ./build.ps1 -t Deploy
    - name: Deploy documents
      uses: JamesIves/github-pages-deploy-action@4.1.5
      with:
        token: ${{ secrets.PA_TOKEN }}
        branch: gh-pages
        folder: ./dist/docs/_site
    # - name: Push API image
    #   uses: docker/build-push-action@v2
    #   with:
    #     context: .
    #     file: ./src/Delights.Api/Dockerfile
    #     push: true
    #     tags: |
    #       stardustdl/delights:api
    # - name: Push client image
    #   uses: docker/build-push-action@v2
    #   with:
    #     context: .
    #     file: ./src/Delights.Client/Dockerfile
    #     push: true
    #     tags: |
    #       stardustdl/delights:client
    # - name: Push WASM host client image
    #   uses: docker/build-push-action@v2
    #   with:
    #     context: .
    #     file: ./src/Delights.Client.WebAssembly.Host/Dockerfile
    #     push: true
    #     tags: |
    #       stardustdl/delights:client-wasm-host